export const POST_TYPES = {
  GET_ALL: 'POST/GET_ALL',
  SET_ALL: 'POST/SET_ALL',
  GET_ONE: 'POST/GET_ONE',
  PATCH: 'POST/PATCH',
  DELETE: 'POST/DELETE',
  CREATE: 'POST/CREATE',
  CLEAR_CURRENT: 'POST/CLEAR_CURRENT',
  SET_ONE: 'POST/SET_ONE',
  SET_LOADING: 'POST/LOADING',
  SET_LOADING_SUCCESS: 'POST/LOADING_SUCCESS',
  SET_LOADING_FAILURE: 'POST/LOADING_FAILURE',
};
