enum TAG_TYPES {
  GET_ALL = 'TAG/GET_ALL',
  SET_ALL = 'TAG/SET_ALL',
  SET_NEW_TAG_NAME = 'TAG/SET_NEW_TAG_NAME',
  ADD_NEW_TAG = 'TAG/ADD_NEW_TAG',
  SET_DELETE_ID = 'TAG/SET_DELETE_ID',
  DELETE_TAG = 'TAG/DELETE',
}

export default TAG_TYPES;
